version: "3.9"
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev   # 👈 explicitly using dev version
    command: bin/rails server -b 0.0.0.0 -p 3000
    volumes:
      - .:/rails
    ports:
      - "3000:3000"
    depends_on:
      - db
    env_file:
      - .env

  db:
    image: postgres:15
    volumes:
      - db-data:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - "5432:5432"

volumes:
  db-data:
