# Default settings for all environments
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

# --------------------------
# Development
# --------------------------
development:
  <<: *default
  database: <%= ENV["DATABASE_NAME"] || "fetchly_development" %>
  username: <%= ENV["DATABASE_USER"] || "postgres" %>
  password: <%= ENV["DATABASE_PASSWORD"] || "" %>
  host: <%= ENV["DATABASE_HOST"] || "localhost" %>
  port: <%= ENV["DATABASE_PORT"] || 5432 %>

# --------------------------
# Test
# --------------------------
test:
  <<: *default
  database: <%= ENV["DATABASE_NAME_TEST"] || "fetchly_test" %>
  username: <%= ENV["DATABASE_USER"] || "postgres" %>
  password: <%= ENV["DATABASE_PASSWORD"] || "" %>
  host: <%= ENV["DATABASE_HOST"] || "localhost" %>
  port: <%= ENV["DATABASE_PORT"] || 5432 %>

# --------------------------
# Production
# --------------------------
production:
  primary: &primary_production
    <<: *default
    database: <%= ENV["DATABASE_NAME"] || "fetchly_production" %>
    username: <%= ENV["DATABASE_USER"] %>
    password: <%= ENV["DATABASE_PASSWORD"] %>
    host: <%= ENV["DATABASE_HOST"] || "localhost" %>
    port: <%= ENV["DATABASE_PORT"] || 5432 %>

  cache:
    <<: *primary_production
    database: <%= ENV["DATABASE_NAME_CACHE"] || "#{ENV["DATABASE_NAME"]}_cache" %>
    migrations_paths: db/cache_migrate

  queue:
    <<: *primary_production
    database: <%= ENV["DATABASE_NAME_QUEUE"] || "#{ENV["DATABASE_NAME"]}_queue" %>
    migrations_paths: db/queue_migrate

  cable:
    <<: *primary_production
    database: <%= ENV["DATABASE_NAME_CABLE"] || "#{ENV["DATABASE_NAME"]}_cable" %>
    migrations_paths: db/cable_migrate
